jjeankim/jogeu-market

- src/lib/axiosInstance.ts
- src/store/AuthStore.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Feat: axios interseptor test중

- src/components/my/MyPageAside.tsx
- src/components/ui/Button.tsx
- src/pages/my/coupons/index.tsx
- 마이페이지 하위 쿠폰페이지 UI 구현
---
---
- 쿠폰 페이지 UI 구현
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> 마이페이지 하위 쿠폰페이지 UI 구현

- src/components/my/OrderTable.tsx
- src/pages/my/orders/index.tsx
---
---
- 주문 표
- 차후 type 정리해야할 것 같습니다. 따로 빼서!
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> feat:OrderTable 테이블 컴포넌트 및 주문내역 확인페이지

- src/components/MainForm.tsx
- src/pages/_app.tsx
- src/pages/order/index.tsx
- 화면비율 고정 (무신사 참고)
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Fix: 특정 비율 이상 화면이 커지지 못하게 전체 화면 비율 고정

- src/pages/_app.tsx
- src/store/AuthStore.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Chore: 메인 페이지 패딩

- src/pages/product/cart/index.tsx
- src/pages/product/new/index.tsx
- 상품 등록 페이지  추가
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> feat:상품등록페이지 추가

- src/components/MainForm.tsx
- src/components/orderForm.tsx
- src/components/ui/Button.tsx
- src/components/ui/ListCard.tsx
- src/lib/apis/product.ts
- src/store/AuthStore.tsx
Feat :  텍스트가 작은 버튼 추가
Fix : 상품 카드 axios -> axiosInstance 수정. 데이터베이스 저장 되는 것 확인.
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Fix :  인증 에러 로그 더 자세히.

- src/components/ui/BrandSlide.tsx
- src/pages/product/index.tsx
- src/styles/swiper.css
- 스와이퍼 6버전에서 11버전으로 변경하여 관련 내용 수정
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Fix: 스와이퍼11버전 업데이트후관련내용  수정

- src/components/Header.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> feature:header navbar

- src/components/MainForm.tsx
- src/components/orderForm.tsx
- src/components/ui/CartForm.tsx
- src/components/ui/CartItemCard.tsx
- src/components/ui/CartPaymentInfo.tsx
- src/components/ui/PayBox.tsx
- src/lib/apis/cart.ts
- src/lib/apis/product.ts
- src/types/cart/cart.ts
fix :  카트 창 버튼 수정
fix : 결제 박스 수정 완료
---
---
- 버튼 컴포넌트 쓰는 페이지에서 수정 완료 
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix : 버튼 컴포넌트 에러 수정 완료

- next.config.ts
- src/components/orderForm.tsx
- src/components/ui/CartForm.tsx
- src/components/ui/CartPaymentInfo.tsx
- src/pages/pay/checkout.tsx
- src/pages/pay/success.tsx
- 장바구니에서 담은 물건이 주문 창에서도 연동 되게 수정함. 
---
---
- 장바구니 수정
- 주문 페이지 수정
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> feat: 주문 데이터 세션 스토리지 저장 및 결제 페이지 데이터 로드 기능 추가

- package-lock.json
- src/components/MainForm.tsx
- src/components/orderForm.tsx
- src/components/payCompleteFrom.tsx
- src/components/ui/PayBox.tsx
- src/lib/apis/order.ts
- src/lib/constants.ts
- src/pages/api/product.ts
- src/pages/pay/success.tsx
fix :  장바구니 -> 주문 -> 결제 -> 결제완료 연동완료
fix ; 주문 데이터베이스에 입력 되는거 확인
---
---
- 주문/결제 연관되는 페이지들 연동 완료
- 데이터베이스에도 정상 등록되는 것 확인 
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> feat: 주문 생성 및 결제 완료 페이지 기능 추가, 쿠폰 적용 및 사용자 정보 로딩 기능 개선

- src/components/QnAForm.tsx
- src/components/payCompleteFrom.tsx
- src/lib/apis/cart.ts
- src/lib/apis/order.ts
- src/pages/pay/checkout.tsx
- src/pages/pay/success.tsx
- 장바구니에서 구매 후 구매한 아이템은 삭제하는 기능
- 주문 번호 모두 통일 
---
---
- 장바구니 로직 수정
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> feat: 주문번호 처리 및 장바구니 아이템 삭제 로깅 추가

- src/components/Pagination.tsx
- src/components/my/review/CustomFileInput.tsx
- src/components/my/review/ReviewCard.tsx
- src/components/my/review/ReviewCardLayout.tsx
- src/components/my/review/ReviewModal.tsx
- src/components/ui/ModalLayout.tsx
- src/hooks/useToast.ts
- src/pages/my/reviews/index.tsx
- src/types/my/order.ts
- 리뷰 작성 기능 구현
---
---
- 리뷰 페이지네이션 기능 제외하고 로컬 이미지 저장까지 구현
---
- 토스트 메세지 가운데 정렬
- 리뷰모달
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Fix: 리뷰 작성 기능 구현

- src/components/DetailForm.tsx
- src/components/orderForm.tsx
- src/components/ui/QnABox.tsx
- src/lib/apis/qna.ts
- src/types/product/qna.ts
- 실제 데이터들로 교체
- 상문 문의 창 구현
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Feat: 상품 문의(QnA) 기능 추가 및 API 연동

- src/components/DetailForm.tsx
- src/components/landing/BrandSection.tsx
- src/components/landing/LandingProductCard.tsx
- src/components/landing/PickProductCard.tsx
- 제품 사진 리사이즈
---
---
- 제품 사진 안 짤리게 수정
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix : 상품 카드 이미지 크기 조정

- src/components/DetailForm.tsx
- src/components/MainForm.tsx
- src/components/landing/BrandSection.tsx
- src/components/landing/LandingProductCard.tsx
- src/components/landing/LandingProductSection.tsx
- src/components/landing/PickProductCard.tsx
- src/components/landing/PickProductSection.tsx
- src/components/my/review/ReviewCardWithStars.tsx
- src/components/product/ProductImage.tsx
- src/components/ui/ListCard.tsx
- src/lib/apis/review.ts
- fix: 랜딩 페이지 pick, new 단일로 변경
- 랜딩페이지 이미지 url 연결
- 상세 페이지 이미지 url 연결
---
---
-랜딩 페이지 pick, new 단일로 변경
- 랜딩페이지 이미지 url 연결
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix: stash 복원 후 작업정리

- src/components/DetailForm.tsx
- src/components/my/review/ReviewCardWithStars.tsx
- src/components/review/ReviewTabContent.tsx
- src/lib/apis/review.ts
- 상품 상세 후기 탭 컴포넌트화 
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix:상품 상세 후기 탭 컴포넌트화 

- src/components/MainForm.tsx
- src/components/my/OrderTable.tsx
- src/components/product/SortBar.tsx
- src/components/ui/SortDropdown.tsx
- src/pages/my/orders/index.tsx
- UI 수정- sortBar, 랜딩 section 너비 조정
---
---
-  sortBar, 랜딩 section 너비 조정
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix:UI 수정- sortBar, 랜딩 section 너비 조정

- src/components/ui/BrandSlide.tsx
- 커스텀 버튼으로 수정
---
---
- 슬라이드 버튼 스타일 수정
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Fix: 슬라이드 버튼 스타일 수정

- .github/workflows/azure-static-web-apps-jolly-tree-0fe5d5400.yml
- next.config.ts
- package.json
- src/styles/swiper.css
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> main deploy test

- src/components/ui/BrandSlide.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix: 브랜드 슬라이드 컴포넌트에서 이미지 URL 속성 수정

- src/components/ui/BrandSlide.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> remove brand type

- src/components/product/BrandSlider.tsx
- src/styles/swiper.css
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Chore:fix  bransSlide css import

- src/components/landing/BrandSection.tsx
- src/components/landing/PickProductSection.tsx
- 메인 페이지 brand 랑 pick 부분 정렬 틀어지는 부분 css 수정
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Fix: 메인 정렬부분 수정

- src/components/landing/PickProductCard.tsx
- src/components/landing/PickProductSection.tsx
- 
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix:모바일 랜딩 pick product 세로형으로 변경

- src/components/ui/ListCard.tsx
- 상품카드에 리뷰있을 시에 리뷰점수 나타나게 연동
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix:ListCard컴포넌트에 별점연동

- src/components/SearchForm.tsx
- src/components/product/DetailInfo.tsx
- src/components/product/ProductImage.tsx
- src/components/ui/CartForm.tsx
- src/components/ui/CartPaymentInfo.tsx
- src/lib/constants.ts
- 상세창에서 보더 빼고 쉐도우로 
---
---
- 제품 상세 창 
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> style: ProductImage 컴포넌트의 스타일을 개선하고 CartForm에서 불필요한 로그 제거

- .github/workflows/azure-static-web-apps-jolly-tree-0fe5d5400.yml
- package-lock.json
- package.json
- src/components/DetailForm.tsx
- src/components/landing/LandingProductSection.tsx
- src/components/my/MyPageLayout.tsx
- src/components/my/MyPageWelcomeCard.tsx
- src/components/my/setting/MypageUserSetting.tsx
- src/components/payCompleteFrom.tsx
- src/components/ui/BrandSlide.tsx
- src/components/ui/CartForm.tsx
- src/components/ui/ListCard.tsx
- src/components/ui/MainCard.tsx
- src/components/ui/Navigator.tsx
- src/components/ui/QnABox.tsx
- src/hooks/useProductActions.ts
- src/lib/apis/cart.ts
- src/lib/apis/order.ts
- src/lib/apis/product.ts
- src/pages/my/coupons/index.tsx
- src/pages/my/reviews/index.tsx
- src/pages/pay/checkout.tsx
- src/pages/pay/success.tsx
- src/pages/product/new/index.tsx
- src/pages/wishlist/index.tsx
- src/store/AuthStore.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Chore: build 수정

- src/components/my/MyPageWelcomeCard.tsx
- src/components/my/review/CustomFileInput.tsx
- src/components/payCompleteFrom.tsx
- src/pages/my/index.tsx
- src/pages/pay/success.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> feat: 결제 완료 페이지 및 마이페이지 컴포넌트의 모바일 및 데스크톱 레이아웃 개선, 스타일 조정 및 정보 표시 추가

- src/components/ui/QnABox.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix: QnABox 컴포넌트에서 불필요한 주석 제거 및 레이아웃 수정

- src/components/Header.tsx
- src/components/SearchForm.tsx
- src/components/my/ProductCardWithHeart.tsx
- src/components/ui/ProductCard.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> "fix: 상품 이미지 카드 깨짐 및 좋아요 리다이렉트 방지"        

- src/components/landing/LandingProductCard.tsx
- src/components/ui/AuthFormLayout.tsx
---
---
- AuthForm : 이미지 가로 비율만 부여 세로 유동적으로 변동하도록 수정
- LandingProductCard : Fill속성 감싸는 요소 relative반영
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> fix:이미지 관련 레이아웃 위험요소 수정

- src/lib/axiosInstance.ts
- src/pages/_app.tsx
- src/store/AuthStore.tsx
---
---
---
---
- Closes #이슈번호
- 관련: #다른이슈
---
> Chore: csrf 설정 변경
